INSERT INTO mapping_specie_macro (specie_pro, macro) VALUES
('fortezza','Urban buildings'),
('scrittoio, stanze annesse alla Porta al Prato','Urban buildings'),
('scala e capanna','Urban buildings'),
('palazzo con cortile, rimessa, scuderia ed annessi','Urban buildings'),
('pastura gelsata','Open spaces (green)'),
('casa, corte e annessi','Urban buildings'),
('uccelliera e fabbrica','Urban buildings'),
('oratorio e compagnia','Religious buildings'),
('vasca e loggia','Urban buildings'),
('casa a terreno e magazzino','Urban buildings'),
('prato cipressato','Open spaces (green)'),
('orto e cappella','Religious buildings'),
('casa a terreno e primo piano','Urban buildings'),
('lavorativo nudo','Open spaces (green)'),
('strada','Open spaces'),
('lavorativo vitato, pioppato, fruttato','Open spaces (green)'),
('fienile','Urban buildings'),
('lavorativo vitato coltivato e ortivo','Open spaces (green)'),
('spezieria','Services'),
('orto a comune','Open spaces (green)'),
('bottega e parte di 1i piano','Commercial'),
('passo a comune','Open spaces'),
('lavorativo gelsato','Open spaces (green)'),
('rimessa e scuderia','Urban buildings'),
('','Open spaces'),
('sodo alberato','Open spaces (green)'),
('stalla e casa','Urban buildings'),
('passare a comune','Urban buildings'),
('sodo gelsato','Open spaces (green)'),
('gora','Waterways'),
('casa a piano','Urban buildings'),
('fontana e vasca','Waterways'),
('bottega e annessi','Commercial'),
('luogo di amministrazione','Services'),
('chiesa e cimitero','Religious buildings'),
('rimessa, corte e fabbricato','Urban buildings'),
('casa e giardinetto','Urban buildings'),
('villa','Urban buildings'),
('pian terreno di una casetta','Urban buildings'),
('vivaio da pioppi','Open spaces (green)'),
('casa, corte e orto','Urban buildings'),
('studio','Commercial'),
('pian terreno','Urban buildings'),
('fabbricato e annessi','Urban buildings'),
('fondo e corte','Urban buildings'),
('sagrestia','Religious buildings'),
('palazzo, corte, rimessa e stalla','Urban buildings'),
('magazzino e fabbricato','Urban buildings'),
('lavorativo con aranci','Open spaces (green)'),
('compagnia detta del Piccione','Religious buildings'),
('fabbricato, corte e bottega','Urban buildings'),
('fabbricato e giardino','Urban buildings'),
('scuole e fabbricato','Urban buildings'),
('stanza terrena','Urban buildings'),
('magazzino e casa','Urban buildings'),
('lavorativo vitato, pomato, fruttato','Open spaces (green)'),
('casa canonica','Urban buildings'),
('palazzo pretorio','Urban buildings'),
('ingresso, casa e corte','Urban buildings'),
('giardino e vasche','Open spaces (green)'),
('lavorativo vitato','Open spaces (green)'),
('terrazza','Urban buildings'),
('seminativo vitato, fruttato','Open spaces (green)'),
('guindolo e corte','Urban buildings'),
('stufa','Urban buildings'),
('spedale e corte','Open spaces'),
('molino','Commercial'),
('bottega, corte e fabbrica','Open spaces'),
('ortivo','Open spaces (green)'),
('lavorativo fruttato vitato','Open spaces (green)'),
('bottega e stanza','Urban buildings'),
('casa e concia','Urban buildings'),
('laguna per il ghiaccio','Waterways'),
('stanza e corte','Urban buildings'),
('casa e ingresso','Urban buildings'),
('casa e due botteghe','Urban buildings'),
('magazzino e stalla','Urban buildings'),
('conciaio e corte','Open spaces'),
('serbatoio e pollaio','Urban buildings'),
('seminativo vitato fruttato','Open spaces (green)'),
('biliardo','Services'),
('fabbricato, fondi e corte','Urban buildings'),
('bagni e corte','Open spaces'),
('concia','Commercial'),
('loggia','Urban buildings'),
('casa e stanze','Urban buildings'),
('casa e forno','Urban buildings'),
('cappella e sagrastia','Religious buildings'),
('casa, magazzino e fabbricato','Urban buildings'),
('fabbricato anzi casa','Urban buildings'),
('casa','Urban buildings'),
('gabellino della Porta Romana con abitazioni','Urban buildings'),
('pioppato fruttato','Open spaces (green)'),
('bottega, corte e fabbricato','Urban buildings'),
('terreno, 1','Open spaces (green)'),
('chiesa e sagrestia','Religious buildings'),
('bottega e stanza sopra','Urban buildings'),
('casetta e rimessa','Urban buildings'),
('palazzo, corte e fabbricato','Urban buildings'),
('bottega e pian terreno','Urban buildings'),
('macelleria','Commercial'),
('magazzino e giardino','Urban buildings'),
('stanza da piante e rimessa','Urban buildings'),
('palazzina','Urban buildings'),
('fabbricato anzi orto','Urban buildings'),
('casa e farmacia','Urban buildings'),
('orto vitato e fruttato','Open spaces (green)'),
('torrino','Urban buildings'),
('giardino, fabbricato e cappella','Urban buildings'),
('casa e orto','Urban buildings'),
('castello','Urban buildings'),
('casa e fabbrica','Urban buildings'),
('casa del giardino','Urban buildings'),
('luoghi comodi, corte e porta','Urban buildings'),
('stradone e passeggio','Open spaces'),
('casino e corte','Urban buildings'),
('casa e rimessa','Urban buildings'),
('orto e casa','Urban buildings'),
('convento e fabbricato','Urban buildings'),
('terreno, magazzino e primo piano','Urban buildings'),
('stalla e stanza','Urban buildings'),
('loggetta e cortile','Open spaces (green)'),
('ingresso comune','Urban buildings'),
('luoghi per dianjaje','Open spaces (green)'),
('fabbrica dell''opera con cortile e annessi','Open spaces (green)'),
('casa, rimessa, corte e piazzale','Urban buildings'),
('palazzetto','Urban buildings'),
('lavorativo vitato, frutteto','Open spaces (green)'),
('prato della fortezza','Urban buildings'),
('ghiacciaia e corte','Open spaces'),
('vicolo','Open spaces'),
('orti','Open spaces (green)'),
('porchereccia','Commercial'),
('bagno','Waterways'),
('stanze','Urban buildings'),
('fabbrica della cera','Commercial'),
('palazzetto, cortile e stalla','Urban buildings'),
('casa e corte','Urban buildings'),
('casa, magazzino e corte','Urban buildings'),
('casa ed ingresso','Urban buildings'),
('labirinto','Open spaces (green)'),
('chiesa','Religious buildings'),
('stalla e passare','Urban buildings'),
('orto olivato','Open spaces (green)'),
('ingresso al piano superiore','Urban buildings'),
('casa e fabbricato','Urban buildings'),
('bottega, casa e corte','Urban buildings'),
('palazzo, corte e rimessa','Urban buildings'),
('edifici','Urban buildings'),
('cantina','Urban buildings'),
('ingresso, casa, corte e fabbricato','Urban buildings'),
('bottega e fondi','Urban buildings'),
('guindolo','Urban buildings'),
('pozzo comune','Waterways'),
('calcinaia','Open spaces'),
('bosco a lecci','Open spaces (green)'),
('vivaio di frutta','Open spaces (green)'),
('stanza a terreno','Urban buildings'),
('massechito','Open spaces (green)'),
('casa e bottega','Urban buildings'),
('andito','Urban buildings'),
('orto e terreno lavorativo','Open spaces (green)'),
('casa al 1n piano con ingresso','Urban buildings'),
('viale in comune','Open spaces'),
('cucina','Urban buildings'),
('bottega e casa','Urban buildings'),
('piano terreno e corte','Open spaces (green)'),
('casa, rimessa e stalla','Urban buildings'),
('conserva d''acqua','Waterways'),
('lavatoio','Waterways'),
('giardinetto','Open spaces (green)'),
('bottega e fornace','Commercial'),
('fabbricato e casa','Urban buildings'),
('chiesa e compagnia','Religious buildings'),
('chiesa e casa','Urban buildings'),
('bottega e orto','Open spaces (green)'),
('lavorativo vitato, pioppato, gelsato','Open spaces (green)'),
('casa colonica','Urban buildings'),
('botteghe','Commercial'),
('prato alberato','Open spaces (green)'),
('sodi','Open spaces (green)'),
('camposanto','Religious buildings'),
('stalla','Commercial'),
('fabbricato e cisterna','Urban buildings'),
('sotterraneo','Urban buildings'),
('piazza e trogoli','Open spaces'),
('lavorativo pioppato','Open spaces (green)'),
('casa, fabbricato e corte','Urban buildings'),
('casa a terreno','Urban buildings'),
('nuovo corridore','Urban buildings'),
('terreno sodivo','Open spaces (green)'),
('terreno','Open spaces (green)'),
('banco e fabbricato','Urban buildings'),
('casa colonica, guindolo e corte','Urban buildings'),
('piantonaia','Open spaces (green)'),
('loggiato','Urban buildings'),
('spedale e corti','Open spaces (green)'),
('giardino con vasche','Open spaces (green)'),
('due botteghe','Commercial'),
('stalla con capanno','Commercial'),
('casa in parte','Urban buildings'),
('casa, corte, rimessa e bottega','Urban buildings'),
('chiesa, sagrestia e orto','Religious buildings'),
('battistero','Religious buildings'),
('sodo olivato, fruttato','Open spaces (green)'),
('casa, rimessa, stalla e corte','Urban buildings'),
('casa e scuderia','Urban buildings'),
('ingresso al giardino e fabbricato','Urban buildings'),
('casa, corte e fabbrica','Urban buildings'),
('bottega e passare','Urban buildings'),
('conciaia e orto','Open spaces (green)'),
('pian terreno e corte','Urban buildings'),
('palazzo e cortile','Urban buildings'),
('palazzo e rimessa','Urban buildings'),
('rimessa e casa','Urban buildings'),
('fornace e corte','Open spaces'),
('pianterreno','Open spaces (green)'),
('prato','Open spaces (green)'),
('pian terreno e mezzanino','Urban buildings'),
('orticello','Open spaces (green)'),
('casa con botteghe e corte','Urban buildings'),
('scuole','Services'),
('casa del giardiniere','Urban buildings'),
('terreno sodo','Open spaces (green)'),
('casa, bottega corte e annessi','Urban buildings'),
('stalla e capanna','Urban buildings'),
('casa e tintoria','Urban buildings'),
('terreno e 13 piano di casa','Urban buildings'),
('lavorativo, vitato, pomato','Open spaces (green)'),
('seminativo','Open spaces (green)'),
('casa interna','Urban buildings'),
('palazzo, corte e scuderia','Urban buildings'),
('loggia a comune','Urban buildings'),
('liceo e corte','Open spaces'),
('ingresso e corte','Urban buildings'),
('albereta','Open spaces (green)'),
('luoghi comodi','Open spaces (green)'),
('fabbricato e orto','Urban buildings'),
('lavorativo vitato e fruttato','Open spaces (green)'),
('giuoco del pallone','Open spaces'),
('scrittoio','Services'),
('camposanto e fabbricato','Urban buildings'),
('commissariato','Services'),
('casa con stalla a comune','Urban buildings'),
('carceri e corte','Open spaces'),
('spalla di Arno','Open spaces'),
('lavorativo olivato','Open spaces (green)'),
('prato comune','Open spaces (green)'),
('palazzetto e corte','Urban buildings'),
('corte e orto','Open spaces (green)'),
('stabile','Urban buildings'),
('ingresso e casa superiormente','Urban buildings'),
('lecceta','Open spaces (green)'),
('arsenale','Urban buildings'),
('polveriera','Urban buildings'),
('corte','Open spaces'),
('casa, corte e bottega','Urban buildings'),
('anfiteatro','Open spaces'),
('cappella e corte','Religious buildings'),
('prato pomario','Open spaces (green)'),
('ghiacciaia','Open spaces'),
('ingresso e casa','Urban buildings'),
('casa, aia e corte','Urban buildings'),
('sodo a pastura','Open spaces (green)'),
('casa e convento','Urban buildings'),
('piazza della cera','Open spaces'),
('gabellino','Urban buildings'),
('casa al 21 piano','Urban buildings'),
('bottega e 33 piano','Commercial'),
('vasca','Waterways'),
('magazzino ed annessi','Urban buildings'),
('stanzone','Urban buildings'),
('chiesa e fabbricato','Urban buildings'),
('casa, corte e magazzino','Urban buildings'),
('cappella e fabbricato','Urban buildings'),
('magazzini e corte','Urban buildings'),
('azienda del bollo','Services'),
('rimessa e terreno','Urban buildings'),
('corte comune','Open spaces'),
('ammazzatoio','Commercial'),
('annesso di spedale','Urban buildings'),
('fabbricato, bottega e aja','Urban buildings'),
('lavorativo vitato, olivato','Open spaces (green)'),
('concimaia','Open spaces'),
('casa a terreno, 1e piano e corte','Urban buildings'),
('magazzino e corti','Urban buildings'),
('orto con stanzetta','Urban buildings'),
('26 e 3  piano','Urban buildings'),
('ingresso e logge','Urban buildings'),
('ospizio','Services'),
('fondi, corte e fabbricato','Urban buildings'),
('orto e corte','Open spaces (green)'),
('casa a terreno e i piani superiori interni','Urban buildings'),
('villino e corte','Urban buildings'),
('caffeaus','Urban buildings'),
('loggia con stanzone','Urban buildings'),
('passeggio pubblico','Open spaces'),
('orto e fabbricato','Urban buildings'),
('viottolo','Open spaces'),
('lavorativo nudo, gelsato','Open spaces (green)'),
('stalla, fienile e corte','Urban buildings'),
('oratorio e sagrestia','Religious buildings'),
('corte e bottega','Open spaces'),
('caserma degli anziani','Services'),
('pian terreno con corte e magazzino','Urban buildings'),
('ingresso e scala','Urban buildings'),
('casa (porzione)','Urban buildings'),
('lavorativo pioppato, fruttato','Open spaces (green)'),
('bottega','Commercial'),
('gabellino e corte','Urban buildings'),
('orto anzi casa','Urban buildings'),
('corridore','Urban buildings'),
('fabbricato e torrione','Urban buildings'),
('vestibolo','Urban buildings'),
('ingresso alla casa','Urban buildings'),
('fabbricato interno','Urban buildings'),
('lavorativo alberato, fruttato','Open spaces (green)'),
('casa, bottega e rimessa','Urban buildings'),
('piazzale','Open spaces'),
('teatro e corte','Open spaces'),
('ingresso e corte a comune','Urban buildings'),
('terreno e 23 piano di casa','Urban buildings'),
('luogo d''adunanza','Open spaces'),
('corpa di guardia','Services'),
('rimessa','Urban buildings'),
('casa e botteghe','Urban buildings'),
('seminario e corte','Religious buildings'),
('palazzo e annessi','Urban buildings'),
('viale','Open spaces'),
('ingresso a comune','Urban buildings'),
('palazzo con cortile, scuderia ed annessi','Urban buildings'),
('aia','Open spaces'),
('guardia e corte','Open spaces'),
('passo e corte','Open spaces'),
('pallottolaio','Services'),
('orto fruttato','Open spaces (green)'),
('fornace','Commercial'),
('capanna','Urban buildings'),
('banco','Commercial'),
('viottole','Open spaces'),
('andito, corte e canonica','Urban buildings'),
('lavatoi','Waterways'),
('casa a terreno e al 1c piano','Urban buildings'),
('convento e spedale','Religious buildings'),
('stufe','Urban buildings'),
('casa colonica, aia e corte','Urban buildings'),
('il fondo bosco','Urban buildings'),
('piazzetta','Open spaces'),
('giardino e fabbricato','Urban buildings'),
('stradone e viottole','Open spaces'),
('casa, bottega e corte','Urban buildings'),
('scuderie','Commercial'),
('rondò e loggiato','Urban buildings'),
('lavorativo vitato, pioppato','Open spaces (green)'),
('chiesa e annessi','Religious buildings'),
('fondi e bottega','Urban buildings'),
('parte di 1t 2c e 3\ piano','Urban buildings'),
('prato pomato con viottole e siepi','Open spaces (green)'),
('scuderie, corte e fabbricato','Urban buildings'),
('casa e capanna','Urban buildings'),
('terreno e corte','Open spaces (green)'),
('sala e ingresso a comune','Urban buildings'),
('prato gelsato','Open spaces (green)'),
('scuole e corte','Open spaces'),
('scuderia','Commercial'),
('ricetto a terreno con scala a comune e 1o piano','Urban buildings'),
('caserma e corte','Open spaces'),
('rimessa e corte','Urban buildings'),
('concia e corte','Open spaces'),
('casa, rimessa e corte','Urban buildings'),
('pastura prativa','Open spaces (green)'),
('casa e fondi','Urban buildings'),
('canonica','Religious buildings'),
('rimessa e mezzanino','Urban buildings'),
('palazzo, corte, rimessa, scuderia ed annessi','Urban buildings'),
('fondi','Urban buildings'),
('casa, bottega e magazzino','Urban buildings'),
('loggia, corte e fabbricato','Urban buildings'),
('luogo del rastrello','Open spaces'),
('casa e corte (porzione)','Urban buildings'),
('palazzo','Urban buildings'),
('piano terreno','Open spaces (green)'),
('orto botanico','Open spaces (green)'),
('oratorio','Religious buildings'),
('villino e guindolo','Urban buildings'),
('passo a comune e corte','Open spaces'),
('casetta e orticello','Urban buildings'),
('ingresso e scuderia','Urban buildings'),
('casa anzi orto','Urban buildings'),
('farmacia','Services'),
('casa, ingresso e corte','Urban buildings'),
('rimessa, stalla e corte','Urban buildings'),
('banco e corte','Open spaces'),
('casamento, botteghe e corte','Urban buildings'),
('bottega e stalla','Commercial'),
('stanzone e loggia','Urban buildings'),
('ingresso e fondi','Urban buildings'),
('rese di detta strada','Open spaces (green)'),
('stalletta','Urban buildings'),
('fabbricato e corte','Urban buildings'),
('stalla e fabbricato','Urban buildings'),
('sodo cipressato','Open spaces (green)'),
('ingresso','Urban buildings'),
('gioco del pallone','Open spaces'),
('stanzino','Urban buildings'),
('gabinetto fisico','Services'),
('magazzino ed orto','Urban buildings'),
('bagnaia','Open spaces'),
('chiasso a comune','Open spaces'),
('pian terreno, corte e fabbricato','Urban buildings'),
('pastura artificiale','Open spaces (green)'),
('casa e cortile','Urban buildings'),
('azienda del registro','Services'),
('fabbricato per uso di rimessa e scuderie','Urban buildings'),
('casamento e corte','Urban buildings'),
('lavorativo gelsato con cipressi','Open spaces (green)'),
('casa, corte e stalla','Urban buildings'),
('fondi e corte','Urban buildings'),
('corte a comune','Open spaces'),
('teatro','Services'),
('campanile','Religious buildings'),
('casamento, rimessa, corte e orto','Urban buildings'),
('magazzino e bottega','Urban buildings'),
('convento','Religious buildings'),
('stanzoni','Urban buildings'),
('corpo di guardia','Services'),
('chiesa, sagrestia e compagnia','Religious buildings'),
('casa,rimessa e corte','Urban buildings'),
('grotta diruta','Urban buildings'),
('casa rurale','Urban buildings'),
('spedale','Services'),
('pian terreno di casa','Urban buildings'),
('lavorativo fruttato','Open spaces (green)'),
('stanzoncino sotterraneo di rotoni','Urban buildings'),
('gabellino e corpo di guardia','Urban buildings'),
('magazzino e corte','Urban buildings'),
('stalla, rimessa e corte','Urban buildings'),
('casa con giardino','Urban buildings'),
('bottega e fabbricato','Urban buildings'),
('magazzino, casa e corte','Urban buildings'),
('piazza','Open spaces'),
('piano terreno (porzione)','Open spaces (green)'),
('sodo','Open spaces (green)'),
('scuola e corte','Open spaces'),
('casa a terreno e corte','Urban buildings'),
('compagnia','Religious buildings'),
('bottega e stanze','Urban buildings'),
('orto con guindolo','Urban buildings'),
('partoria','Services'),
('parterre','Open spaces (green)'),
('casa, corte e fabbricato','Urban buildings'),
('conservatorio','Waterways'),
('casa e corte parte di 3','Urban buildings'),
('siti','Urban buildings'),
('seminativo vitato, olivato','Open spaces (green)'),
('casa e stalla','Urban buildings'),
('recinto alla Porta S. Giorgio','Urban buildings'),
('boschetto','Open spaces (green)'),
('bottega (porzione)','Commercial'),
('casa a terreno e 1r piano','Urban buildings'),
('lavorativo vitato, fruttato e olivato','Open spaces (green)'),
('palazzo con corte, rimessa e annessi','Urban buildings'),
('prato e uccelliera','Urban buildings'),
('prativo','Open spaces (green)'),
('scala a comune','Urban buildings'),
('rimessa, corte e stalla','Urban buildings'),
('pollaio','Urban buildings'),
('fondi e botteghe','Urban buildings'),
('osteria e fabbricato','Urban buildings'),
('pastura alberata','Open spaces (green)'),
('stanze del peso pubblico','Urban buildings'),
('compagnia e corte','Religious buildings'),
('terreno e 13 piano','Open spaces (green)'),
('canonica e convento','Religious buildings'),
('magazzini','Urban buildings'),
('stanza mortuaria','Urban buildings'),
('cappella','Religious buildings'),
('orto, corte e fabbricato','Urban buildings'),
('casamento','Urban buildings'),
('bottega e corte','Open spaces'),
('libreria','Services'),
('fabbricato e corte a comune','Urban buildings'),
('giardino','Open spaces (green)'),
('rimessa e stalla','Urban buildings'),
('lavorativo vitato, pioppato con frutti','Open spaces (green)'),
('casa a terreno, corte e magazzino','Urban buildings'),
('rondC e loggiato','Urban buildings'),
('rimessa e fienile','Urban buildings'),
('fabbricato (porzione)','Urban buildings'),
('loggia (porzione)','Urban buildings'),
('vasca e giardino','Open spaces (green)'),
('nicchia prativa','Open spaces (green)'),
('stalla e magazzino','Urban buildings'),
('lavorativo vitato, pioppato e olivato','Open spaces (green)'),
('scuola','Services'),
('canneto','Open spaces (green)'),
('rimessa (porzione)','Urban buildings'),
('fabbricato','Urban buildings'),
('corte e fabbricato','Urban buildings'),
('ingresso e fabbricato','Urban buildings'),
('loggia e fabbricato','Urban buildings'),
('passare e casa','Urban buildings'),
('suolo a pastura','Open spaces (green)'),
('androne','Urban buildings'),
('viottola','Open spaces'),
('palazzo, rimessa, scuderia e corte','Urban buildings'),
('casa, corte e rimessa','Urban buildings'),
('fabbrica','Commercial'),
('andito e corte','Urban buildings'),
('casa e passare','Urban buildings'),
('stanza dei gabellini','Urban buildings'),
('cimitero','Religious buildings'),
('due stanze','Urban buildings'),
('scuderie e corte','Open spaces'),
('bosco','Open spaces (green)'),
('passare e corte','Urban buildings'),
('caserma','Services'),
('gabellino e torre','Urban buildings'),
('monastero','Religious buildings'),
('plantarnari','Open spaces (green)'),
('torre','Urban buildings'),
('casa e corte a comune','Urban buildings'),
('sodo e piazza','Open spaces (green)'),
('sito coperto','Urban buildings'),
('pian terreno e 1p piano','Urban buildings'),
('pastura','Open spaces (green)'),
('stradella','Open spaces'),
('casa, corte e casotto','Urban buildings'),
('stanzone e vasca','Urban buildings'),
('orto vitato e pomato','Open spaces (green)'),
('villino','Urban buildings'),
('stanza a terreno e sotterranei','Urban buildings'),
('uccelliera','Urban buildings'),
('lavorativo vitato, olivato, fruttato','Open spaces (green)'),
('lav (lavorativo) spogliato','Open spaces (green)'),
('sodivo con gelsi','Open spaces (green)'),
('palazzo, rimessa e cortile','Urban buildings'),
('ingresso all''orto','Urban buildings'),
('androne e casa','Urban buildings'),
('spiazzo','Open spaces'),
('caffeaus e corte','Urban buildings'),
('viali','Open spaces'),
('seminativo fruttato','Open spaces (green)'),
('bosco ceduo','Open spaces (green)'),
('forno e magazzino','Urban buildings'),
('casa da lavorativo','Urban buildings'),
('ingresso, corte e casa','Urban buildings'),
('bindolo','Waterways'),
('casa e annessi','Urban buildings'),
('quartiere e corte','Urban buildings'),
('luogo di delizia','Open spaces (green)'),
('orto e bottega','Open spaces (green)'),
('parte di una concia','Commercial'),
('parte di pian terreno','Urban buildings'),
('terreno e casa','Urban buildings'),
('palazzo e corte','Urban buildings'),
('stanze d''uso di stalla','Urban buildings'),
('rimessa e bottega','Urban buildings'),
('sala di artifizio','Urban buildings'),
('lavorativo vitato, pomato','Open spaces (green)'),
('sodo fruttato, olivato','Open spaces (green)'),
('convento e corte','Religious buildings'),
('madiella','Commercial'),
('stanza','Urban buildings'),
('casino','Urban buildings'),
('stalla e corte','Open spaces'),
('chiesa e corte','Religious buildings'),
('stradello e viale','Open spaces'),
('magazzino (porzione)','Urban buildings'),
('magazzino','Urban buildings'),
('casa, terreno e corte','Urban buildings'),
('palazzo con rimessa, scuderia ed annessi','Urban buildings'),
('lavorativo con piantoni di olivo','Open spaces (green)'),
('infermeria','Services'),
('metropolitana','Open spaces'),
('arsenale, rimessa e corte','Urban buildings'),
('orto vitato, fruttato','Open spaces (green)'),
('orto e stanzone','Urban buildings'),
('bottega e magazzino','Urban buildings'),
('stalla e rimessa','Urban buildings'),
('tabernacolo','Religious buildings'),
('lavorativo vitato, fruttato','Open spaces (green)'),
('stanza dell''anziano','Urban buildings'),
('casa e corticella','Urban buildings'),
('casa e magazzino','Urban buildings'),
('spezieria e corte','Open spaces'),
('stabile (porzione)','Urban buildings'),
('granaio','Urban buildings'),
('grotta','Urban buildings'),
('casa per i cappellani','Urban buildings'),
('teatro e stanza annessa','Urban buildings'),
('quartiere','Urban buildings'),
('casetta','Urban buildings'),
('fabbricato per gli agrari','Urban buildings'),
('luogo di comodo','Commercial'),
('rimessa, cortile e annessi','Urban buildings'),
('casamento con forni annessi','Urban buildings'),
('fonte','Waterways'),
('casa, bottega e forno','Urban buildings'),
('farmacia e orto','Open spaces (green)'),
('casa e ingresso a comune','Urban buildings'),
('teatro e annessi','Services'),
('fabbricato per la cascina','Urban buildings'),
('oratorio, compagnia e annessi','Religious buildings'),
('orto','Open spaces (green)'),
('stanzone e corte','Urban buildings'),
('guindolo e aia','Urban buildings'),
('pratello','Open spaces (green)'),
('lavorativo coltivato','Open spaces (green)')
;
